Neos:
  Neos:
    fusion:
      autoInclude:
        Futape.NodeTypes: true
    userInterface:
      translation:
        autoInclude:
          Futape.NodeTypes:
            - 'NodeTypes/*'
            - 'Overrides/*'
